-- MySQL Script generated by MySQL Workbench
-- Wed Sep  1 03:04:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema LOCALIZA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LOCALIZA` ;

-- -----------------------------------------------------
-- Schema LOCALIZA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LOCALIZA` DEFAULT CHARACTER SET utf8mb4 ;
USE `LOCALIZA` ;

-- -----------------------------------------------------
-- Table `LOCALIZA`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIZA`.`Marca` ;

CREATE TABLE IF NOT EXISTS `LOCALIZA`.`Marca` (
  `nMarcaID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `strDescricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nMarcaID`));


-- -----------------------------------------------------
-- Table `LOCALIZA`.`Modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIZA`.`Modelo` ;

CREATE TABLE IF NOT EXISTS `LOCALIZA`.`Modelo` (
  `nModeloID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `strDescricao` VARCHAR(45) NULL DEFAULT NULL,
  `nID_Marca` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`nModeloID`));


-- -----------------------------------------------------
-- Table `LOCALIZA`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIZA`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `LOCALIZA`.`Veiculo` (
  `nVeiculoID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `strPlaca` VARCHAR(45) NULL DEFAULT NULL,
  `strChassi` VARCHAR(45) NULL DEFAULT NULL,
  `strRenavan` VARCHAR(45) NULL DEFAULT NULL,
  `strCor` VARCHAR(45) NULL DEFAULT NULL,
  `dtAno` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`nVeiculoID`));


-- -----------------------------------------------------
-- Table `LOCALIZA`.`Seguro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIZA`.`Seguro` ;

CREATE TABLE IF NOT EXISTS `LOCALIZA`.`Seguro` (
  `nSeguroID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `strApolice` VARCHAR(45) NULL DEFAULT NULL,
  `strValor` DECIMAL(6,2) NULL DEFAULT NULL,
  `dtVencimento` DATE NULL DEFAULT NULL,
  `nIDVEICULO` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`nSeguroID`));


-- -----------------------------------------------------
-- Table `LOCALIZA`.`Manutencao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIZA`.`Manutencao` ;

CREATE TABLE IF NOT EXISTS `LOCALIZA`.`Manutencao` (
  `nManuntencaoID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `strTipo` ENUM('PREVENTIVA', 'CORRETIVA') NULL DEFAULT NULL,
  `strKm` INT NULL DEFAULT NULL,
  `dtDATA` DATE NULL DEFAULT NULL,
  `strDescricao` VARCHAR(100) NULL DEFAULT NULL,
  `nIDVeiculo` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`nManuntencaoID`));


-- -----------------------------------------------------
-- Table `LOCALIZA`.`Realizado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIZA`.`Realizado` ;

CREATE TABLE IF NOT EXISTS `LOCALIZA`.`Realizado` (
  `nRealizadoID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `strDescricao` VARCHAR(45) NULL DEFAULT NULL,
  `strValor` DECIMAL(6,2) NULL DEFAULT NULL,
  `nIDManutencao` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`nRealizadoID`));


-- -----------------------------------------------------
-- Table `LOCALIZA`.`Locatario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIZA`.`Locatario` ;

CREATE TABLE IF NOT EXISTS `LOCALIZA`.`Locatario` (
  `nLocatarioID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `strNome` VARCHAR(80) NULL DEFAULT NULL,
  `strTipo` ENUM('pj', 'pf') NULL DEFAULT NULL,
  `strCpf_Cnpj` VARCHAR(45) NULL DEFAULT NULL,
  `strRua` VARCHAR(45) NULL DEFAULT NULL,
  `strNumero` VARCHAR(45) NULL DEFAULT NULL,
  `strComplemento` VARCHAR(45) NULL DEFAULT NULL,
  `strCep` VARCHAR(45) NULL DEFAULT NULL,
  `strBairro` VARCHAR(45) NULL DEFAULT NULL,
  `strCidade` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nLocatarioID`));


-- -----------------------------------------------------
-- Table `LOCALIZA`.`Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIZA`.`Telefone` ;

CREATE TABLE IF NOT EXISTS `LOCALIZA`.`Telefone` (
  `nTelefoneID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `srtTipo` VARCHAR(45) NULL DEFAULT NULL,
  `srtDdd` VARCHAR(3) NULL DEFAULT NULL,
  `srtNumero` VARCHAR(45) NULL DEFAULT NULL,
  `nIDLocatario` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`nTelefoneID`));


-- -----------------------------------------------------
-- Table `LOCALIZA`.`Locacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCALIZA`.`Locacao` ;

CREATE TABLE IF NOT EXISTS `LOCALIZA`.`Locacao` (
  `nLocacaoID` INT UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT,
  `dtLocacao` DATETIME NULL DEFAULT NULL,
  `dtDevolucao_prev` DATETIME NULL DEFAULT NULL,
  `srtKmInicial` INT NULL DEFAULT NULL,
  `srtKmFinal` INT NULL DEFAULT NULL,
  `srtValor` DOUBLE(6,2) NULL DEFAULT NULL,
  `srtObservacoes` LONGTEXT NULL DEFAULT NULL,
  `nIDLocatario` INT UNSIGNED NULL DEFAULT NULL,
  `nIDVeiculo` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`nLocacaoID`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
